disabled_rules: # ここに無効にしたいルールを追加します

opt_in_rules: # ここに有効にしたいオプトインルールを追加します
  - empty_count
  - explicit_init
  - line_length
  - trailing_whitespace
  - force_unwrapping
  - nesting
  - identifier_name
  - cyclomatic_complexity
  - function_body_length

included: # ここに解析対象のファイルやディレクトリを追加します
  - Sample

excluded: # ここに解析対象外のファイルやディレクトリを追加します

# 各ルールのカスタマイズ
line_length:
  warning: 120
  error: 200

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

force_unwrapping:
  severity: error

nesting:
  type_level: 2
  severity: warning

identifier_name:
  min_length: 2

cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 20
  error: 100

custom_rules:
  weak_self_closure:
  included: ".*.swift"
  name: "Use weak self in closures"
  message: "Use weak self when create a closure."
  regex: "\\{\\s*[^\\[]{0,50}\\s+\\bin\\b([a-zA-Z\\\\.\\(\\)\\[\\{\\}\\>\\/\\=]|\\s)+(self)[^!]"
  severity: error