disabled_rules: # ここに無効にしたいルールを追加します
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_imports
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_parameter_count
  - generic_type_name
  - implicit_getter
  - is_disjoint
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions 
  - mark
  - multiple_closures_with_trailing_closure
  - no_fallthrough_only
  - notification_center_detachment
  - opening_brace
  - operator_whitespace
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message

opt_in_rules: # ここに有効にしたいオプトインルールを追加します
  - empty_count
  - explicit_init
  - line_length
  - trailing_whitespace
  - force_unwrapping
  - nesting
  - identifier_name
  - cyclomatic_complexity
  - function_body_length

included: # ここに解析対象のファイルやディレクトリを追加します
  - Sample

excluded: # ここに解析対象外のファイルやディレクトリを追加します

# 各ルールのカスタマイズ
line_length:
  warning: 120
  error: 200

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

force_unwrapping:
  severity: error

nesting:
  type_level: 2

identifier_name:
  min_length: 2

cyclomatic_complexity:
  warning: 10
  error: 20

function_body_length:
  warning: 20
  error: 100

custom_rules:
  weak_self_closure:
  included: ".*.swift"
  name: "Use weak self in closures"
  message: "Use weak self when create a closure."
  regex: "\\{\\s*[^\\[]{0,50}\\s+\\bin\\b([a-zA-Z\\\\.\\(\\)\\[\\{\\}\\>\\/\\=]|\\s)+(self)[^!]"
  severity: error